import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'Patschi Backend',
    'app.subtitle': 'Admin Dashboard',
    'app.reservation_system': 'Reservation Management System',
    'nav.home': 'Home',
    'nav.floor_plan': 'Floor Plan',
    'nav.reservations': 'Reservations',
    'nav.settings': 'Settings',
    'nav.sign_out': 'Sign Out',
    'login.title': 'Patschi Backend',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.sign_in': 'Sign In',
    'login.signing_in': 'Signing in...',
    'login.error': 'Invalid email or password',
    'login.placeholder_email': 'admin@patschi.com',
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'Dashboard Overview',
    'dashboard.today_reservations': 'Today\'s Reservations',
    'dashboard.upcoming_reservations': 'Upcoming Reservations',
    'dashboard.total_tables': 'Total Tables',
    'dashboard.available_tables': 'Available Tables',
    'dashboard.recent_reservations': 'Recent Reservations',
    'dashboard.view_all': 'View All Reservations',
    'dashboard.no_reservations': 'No reservations for today',
    'dashboard.total_reservations': 'Total Reservations',
    'dashboard.total_guests': 'Total Guests',
    'dashboard.total_revenue': 'Total Revenue',
    'dashboard.confirmed': 'Confirmed',
    'dashboard.pending': 'Pending',
    'dashboard.cancelled': 'Cancelled',
    'dashboard.average_party_size': 'Average Party Size',
    'dashboard.peak_hours': 'Peak Hours',
    'dashboard.daily_statistics': 'Daily Statistics',
    'dashboard.last_10_days': 'Last 10 Days',
    'dashboard.confirmed_bookings': 'Confirmed bookings',
    'dashboard.pending_bookings': 'Pending bookings',
    'dashboard.cancelled_bookings': 'Cancelled bookings',
    'dashboard.avg_daily_revenue': 'Avg Daily Revenue',
    'dashboard.avg_per_booking': 'Avg',
    'dashboard.per_booking': 'per booking',
    'dashboard.bookings': 'bookings',
    'dashboard.reservation_status': 'Reservation Status',
    'dashboard.active_bookings': 'Active bookings',
    'dashboard.awaiting_confirmation': 'Awaiting confirmation',
    'dashboard.peak_booking_hours': 'Peak Booking Hours',
    'dashboard.daily_breakdown': 'Daily Breakdown',
    'dashboard.date': 'Date',
    'dashboard.reservations': 'Reservations',
    'dashboard.revenue': 'Revenue',
    'reservations.title': 'Reservation Management',
    'reservations.today': 'Today',
    'reservations.upcoming': 'Upcoming',
    'reservations.all': 'All',
    'reservations.date': 'Date',
    'reservations.clear_date': 'Clear Date',
    'reservations.guests': 'guests',
    'reservations.table': 'Table',
    'reservations.tables': 'Tables',
    'reservations.select_room_first': 'Please select a room first',
    'reservations.no_tables_available': 'No tables available in this room',
    'reservations.special_requests': 'Special Requests',
    'reservations.no_reservations': 'No reservations found',
    'reservations.update_status': 'Update Reservation Status',
    'reservations.confirm': 'Confirm Reservation',
    'reservations.complete': 'Mark as Completed',
    'reservations.cancel': 'Cancel Reservation',
    'reservations.delete': 'Delete Reservation',
    'reservations.confirm_delete': 'Are you sure you want to permanently delete this reservation? This action cannot be undone.',
    'reservations.close': 'Close',
    'reservations.create': 'Create Reservation',
    'reservations.select_room': 'Select Room (Optional)',
    'reservations.select_table': 'Select Table (Optional)',
    'reservations.status': 'Reservation Status',
    'reservations.payment_status': 'Payment Status',
    'reservations.payment_amount': 'Payment Amount (€)',
    'reservations.payment_management': 'Payment Management',
    'reservations.status_confirmed': 'confirmed',
    'reservations.status_cancelled': 'cancelled',
    'reservations.status_completed': 'completed',
    'reservations.status_pending': 'pending',
    'reservations.payment_paid': 'paid',
    'reservations.payment_pending': 'pending',
    'reservations.payment_refunded': 'refunded',
    'floor_plan.title': 'Floor Plan & Tables',
    'floor_plan.add_table': 'Add Table',
    'floor_plan.table_number': 'Table Number',
    'floor_plan.capacity': 'Capacity',
    'floor_plan.location': 'Location',
    'floor_plan.available': 'Available',
    'floor_plan.occupied': 'Occupied',
    'floor_plan.reserved': 'Reserved',
    'floor_plan.save': 'Save Table',
    'floor_plan.cancel': 'Cancel',
    'floor_plan.delete': 'Delete Table',
    'floor_plan.edit': 'Edit',
    'floor_plan.print': 'Print',
    'floor_plan.edit_table': 'Edit Table',
    'floor_plan.seats': 'seats',
    'settings.title': 'Settings',
    'settings.rooms': 'Room Settings',
    'settings.email': 'Email Settings',
    'settings.widget': 'Widget Settings',
    'settings.booking_hours': 'Booking Hours',
    'settings.stripe': 'Stripe Settings',
    'room.manage_rooms': 'Manage Rooms',
    'room.add_room': 'Add New Room',
    'room.room_name': 'Room Name',
    'room.description': 'Description',
    'room.save': 'Save Room',
    'room.cancel': 'Cancel',
    'room.delete': 'Delete Room',
    'room.edit': 'Edit',
    'room.no_rooms': 'No rooms configured',
    'email.title': 'Email Settings',
    'email.from_name': 'From Name',
    'email.subject': 'Email Subject',
    'email.body': 'Email Body',
    'email.save': 'Save Settings',
    'email.saved': 'Settings saved successfully!',
    'email.placeholder_name': 'Patschi',
    'email.placeholder_subject': 'Your Reservation Confirmation',
    'widget.title': 'Widget Settings',
    'widget.embed_code': 'Embed Code',
    'widget.copy_code': 'Copy and paste this code into your website where you want the reservation widget to appear.',
    'widget.copy': 'Copy to Clipboard',
    'widget.copied': 'Copied!',
    'widget.preview': 'Preview Widget',
    'widget.direct_link': 'Direct Widget Link',
    'widget.share_link': 'Share this link with customers to access the reservation widget directly.',
    'booking_hours.title': 'Booking Hours',
    'booking_hours.day': 'Day',
    'booking_hours.enabled': 'Enabled',
    'booking_hours.open': 'Open',
    'booking_hours.close': 'Close',
    'booking_hours.save': 'Save Hours',
    'booking_hours.saved': 'Booking hours saved successfully!',
    'booking_hours.monday': 'Monday',
    'booking_hours.tuesday': 'Tuesday',
    'booking_hours.wednesday': 'Wednesday',
    'booking_hours.thursday': 'Thursday',
    'booking_hours.friday': 'Friday',
    'booking_hours.saturday': 'Saturday',
    'booking_hours.sunday': 'Sunday',
    'stripe.title': 'Stripe Settings',
    'stripe.secret_key': 'Stripe Secret Key',
    'stripe.deposit_amount': 'Deposit Amount',
    'stripe.currency': 'Currency',
    'stripe.save': 'Save Settings',
    'stripe.saved': 'Stripe settings saved successfully!',
    'reservation_widget.title': 'Reserve Your Table',
    'reservation_widget.subtitle': 'Book your reservation with Patschi',
    'reservation_widget.step_date': 'Date & Time',
    'reservation_widget.step_details': 'Your Details',
    'reservation_widget.step_confirm': 'Confirmation',
    'reservation_widget.select_date': 'Select Date',
    'reservation_widget.select_time': 'Select Time',
    'reservation_widget.party_size': 'Party Size',
    'reservation_widget.select_room': 'Select Room',
    'reservation_widget.next': 'Next',
    'reservation_widget.back': 'Back',
    'reservation_widget.name': 'Full Name',
    'reservation_widget.email': 'Email',
    'reservation_widget.phone': 'Phone (optional)',
    'reservation_widget.special_requests': 'Special Requests (optional)',
    'reservation_widget.confirm_booking': 'Confirm Booking',
    'reservation_widget.success': 'Reservation Confirmed!',
    'reservation_widget.success_message': 'Your reservation has been confirmed. You will receive a confirmation email shortly.',
    'reservation_widget.new_reservation': 'Make Another Reservation',
    'reservation_widget.closed': 'We are closed on this day',
    'reservation_widget.no_times': 'No available times for the selected date',
    'gift_card.title': 'Gift Card System',
    'gift_card.subtitle': 'Manage gift cards & vouchers',
    'gift_card.home': 'Home',
    'gift_card.create_card': 'Create Card',
    'gift_card.manage_cards': 'Manage Cards',
    'gift_card.settings': 'Settings',
    'gift_card.dashboard': 'Gift Card Dashboard',
    'gift_card.total_sold': 'Total Gift Cards Sold',
    'gift_card.total_revenue': 'Total Revenue',
    'gift_card.active_cards': 'Active Gift Cards',
    'gift_card.redeemed_cards': 'Redeemed Cards',
    'gift_card.recent_sales': 'Recent Gift Card Sales',
    'gift_card.view_all': 'View All Gift Cards',
    'gift_card.no_sales': 'No gift cards sold yet',
    'gift_card.code': 'Code',
    'gift_card.amount': 'Amount',
    'gift_card.status': 'Status',
    'gift_card.status_active': 'Active',
    'gift_card.status_redeemed': 'Redeemed',
    'gift_card.status_expired': 'Expired',
    'gift_card.purchased_by': 'Purchased by',
    'gift_card.recipient': 'Recipient',
    'gift_card.balance': 'Balance',
    'gift_card.created_date': 'Created',
    'gift_card.expiry_date': 'Expires',
    'gift_card.overview': 'Overview of your gift card system',
    'gift_card.total_value': 'Total Value',
    'gift_card.active_gift_cards': 'Active gift cards',
    'gift_card.total_cards': 'Total Cards',
    'gift_card.issued_cards': 'Issued cards',
    'gift_card.redeemed': 'Redeemed',
    'gift_card.cards_used': 'Cards used',
    'system_selector.title': 'Select Management System',
    'system_selector.subtitle': 'Choose which system you want to manage',
    'system_selector.select_system': 'Select System',
    'system_selector.reservation_title': 'Reservation System',
    'system_selector.reservation_desc': 'Manage table reservations, floor plans, and booking hours',
    'system_selector.gift_card_title': 'Gift Card Management',
    'system_selector.gift_card_desc': 'Create, track, and manage gift cards and vouchers',
    'crew.floor_plan': 'Floor Plan',
    'crew.reservations': 'Reservations',
    'crew.optional': 'optional',
    'crew.book_multiple_days': 'Book for multiple days',
    'crew.book_additional_days': 'Book additional days',
    'crew.select_days': 'Select Days',
    'crew.days_selected': 'day(s) selected',
    'crew.additional_reservations_note': '(additional reservations will be created)',
    'crew.update': 'Update',
    'crew.confirm_delete': 'Are you sure you want to delete this reservation?',
    'crew.reservation': 'reservation',
    'crew.reservations_plural': 'reservations',
    'crew.paid_with_cash': 'Paid with cash',
    'crew.cash_amount': 'Cash Amount (€)',
  },
  de: {
    'app.title': 'Patschi Backend',
    'app.subtitle': 'Admin Dashboard',
    'app.reservation_system': 'Reservierungsverwaltungssystem',
    'nav.home': 'Startseite',
    'nav.floor_plan': 'Raumplan',
    'nav.reservations': 'Reservierungen',
    'nav.settings': 'Einstellungen',
    'nav.sign_out': 'Abmelden',
    'login.title': 'Patschi Backend',
    'login.email': 'E-Mail-Adresse',
    'login.password': 'Passwort',
    'login.sign_in': 'Anmelden',
    'login.signing_in': 'Wird angemeldet...',
    'login.error': 'Ungültige E-Mail oder Passwort',
    'login.placeholder_email': 'admin@patschi.com',
    'dashboard.welcome': 'Willkommen zurück',
    'dashboard.overview': 'Dashboard-Übersicht',
    'dashboard.today_reservations': 'Heutige Reservierungen',
    'dashboard.upcoming_reservations': 'Kommende Reservierungen',
    'dashboard.total_tables': 'Tische Gesamt',
    'dashboard.available_tables': 'Verfügbare Tische',
    'dashboard.recent_reservations': 'Letzte Reservierungen',
    'dashboard.view_all': 'Alle Reservierungen anzeigen',
    'dashboard.no_reservations': 'Keine Reservierungen für heute',
    'dashboard.total_reservations': 'Reservierungen Gesamt',
    'dashboard.total_guests': 'Gäste Gesamt',
    'dashboard.total_revenue': 'Gesamtumsatz',
    'dashboard.confirmed': 'Bestätigt',
    'dashboard.pending': 'Ausstehend',
    'dashboard.cancelled': 'Storniert',
    'dashboard.average_party_size': 'Durchschnittliche Gruppengröße',
    'dashboard.peak_hours': 'Stoßzeiten',
    'dashboard.daily_statistics': 'Tägliche Statistiken',
    'dashboard.last_10_days': 'Letzte 10 Tage',
    'dashboard.confirmed_bookings': 'Bestätigte Buchungen',
    'dashboard.pending_bookings': 'Ausstehende Buchungen',
    'dashboard.cancelled_bookings': 'Stornierte Buchungen',
    'dashboard.avg_daily_revenue': 'Durchschnittlicher Tagesumsatz',
    'dashboard.avg_per_booking': 'Durchschn',
    'dashboard.per_booking': 'pro Buchung',
    'dashboard.bookings': 'Buchungen',
    'dashboard.reservation_status': 'Reservierungsstatus',
    'dashboard.active_bookings': 'Aktive Buchungen',
    'dashboard.awaiting_confirmation': 'Wartet auf Bestätigung',
    'dashboard.peak_booking_hours': 'Stoßzeiten für Buchungen',
    'dashboard.daily_breakdown': 'Tägliche Aufschlüsselung',
    'dashboard.date': 'Datum',
    'dashboard.reservations': 'Reservierungen',
    'dashboard.revenue': 'Umsatz',
    'reservations.title': 'Reservierungsverwaltung',
    'reservations.today': 'Heute',
    'reservations.upcoming': 'Kommend',
    'reservations.all': 'Alle',
    'reservations.date': 'Datum',
    'reservations.clear_date': 'Datum löschen',
    'reservations.guests': 'Gäste',
    'reservations.table': 'Tisch',
    'reservations.tables': 'Tische',
    'reservations.select_room_first': 'Bitte zuerst einen Raum auswählen',
    'reservations.no_tables_available': 'Keine Tische in diesem Raum verfügbar',
    'reservations.special_requests': 'Besondere Wünsche',
    'reservations.no_reservations': 'Keine Reservierungen gefunden',
    'reservations.update_status': 'Reservierungsstatus aktualisieren',
    'reservations.confirm': 'Reservierung bestätigen',
    'reservations.complete': 'Als abgeschlossen markieren',
    'reservations.cancel': 'Reservierung stornieren',
    'reservations.delete': 'Reservierung löschen',
    'reservations.confirm_delete': 'Sind Sie sicher, dass Sie diese Reservierung dauerhaft löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'reservations.close': 'Schließen',
    'reservations.create': 'Reservierung erstellen',
    'reservations.select_room': 'Raum auswählen (Optional)',
    'reservations.select_table': 'Tisch auswählen (Optional)',
    'reservations.status': 'Reservierungsstatus',
    'reservations.payment_status': 'Zahlungsstatus',
    'reservations.payment_amount': 'Zahlungsbetrag (€)',
    'reservations.payment_management': 'Zahlungsverwaltung',
    'reservations.status_confirmed': 'bestätigt',
    'reservations.status_cancelled': 'storniert',
    'reservations.status_completed': 'abgeschlossen',
    'reservations.status_pending': 'ausstehend',
    'reservations.payment_paid': 'bezahlt',
    'reservations.payment_pending': 'ausstehend',
    'reservations.payment_refunded': 'erstattet',
    'floor_plan.title': 'Raumplan & Tische',
    'floor_plan.add_table': 'Tisch hinzufügen',
    'floor_plan.table_number': 'Tischnummer',
    'floor_plan.capacity': 'Kapazität',
    'floor_plan.location': 'Standort',
    'floor_plan.available': 'Verfügbar',
    'floor_plan.occupied': 'Besetzt',
    'floor_plan.reserved': 'Reserviert',
    'floor_plan.save': 'Tisch speichern',
    'floor_plan.cancel': 'Abbrechen',
    'floor_plan.delete': 'Tisch löschen',
    'floor_plan.edit': 'Bearbeiten',
    'floor_plan.print': 'Drucken',
    'floor_plan.edit_table': 'Tisch bearbeiten',
    'floor_plan.seats': 'Plätze',
    'settings.title': 'Einstellungen',
    'settings.rooms': 'Raumeinstellungen',
    'settings.email': 'E-Mail-Einstellungen',
    'settings.widget': 'Widget-Einstellungen',
    'settings.booking_hours': 'Buchungszeiten',
    'settings.stripe': 'Stripe-Einstellungen',
    'room.manage_rooms': 'Räume verwalten',
    'room.add_room': 'Neuen Raum hinzufügen',
    'room.room_name': 'Raumname',
    'room.description': 'Beschreibung',
    'room.save': 'Raum speichern',
    'room.cancel': 'Abbrechen',
    'room.delete': 'Raum löschen',
    'room.edit': 'Bearbeiten',
    'room.no_rooms': 'Keine Räume konfiguriert',
    'email.title': 'E-Mail-Einstellungen',
    'email.from_name': 'Absendername',
    'email.subject': 'E-Mail-Betreff',
    'email.body': 'E-Mail-Text',
    'email.save': 'Einstellungen speichern',
    'email.saved': 'Einstellungen erfolgreich gespeichert!',
    'email.placeholder_name': 'Patschi',
    'email.placeholder_subject': 'Ihre Reservierungsbestätigung',
    'widget.title': 'Widget-Einstellungen',
    'widget.embed_code': 'Einbettungscode',
    'widget.copy_code': 'Kopieren Sie diesen Code und fügen Sie ihn auf Ihrer Website ein, wo das Reservierungs-Widget erscheinen soll.',
    'widget.copy': 'In Zwischenablage kopieren',
    'widget.copied': 'Kopiert!',
    'widget.preview': 'Widget-Vorschau',
    'widget.direct_link': 'Direkter Widget-Link',
    'widget.share_link': 'Teilen Sie diesen Link mit Kunden, um direkt auf das Reservierungs-Widget zuzugreifen.',
    'booking_hours.title': 'Buchungszeiten',
    'booking_hours.day': 'Tag',
    'booking_hours.enabled': 'Aktiviert',
    'booking_hours.open': 'Öffnen',
    'booking_hours.close': 'Schließen',
    'booking_hours.save': 'Zeiten speichern',
    'booking_hours.saved': 'Buchungszeiten erfolgreich gespeichert!',
    'booking_hours.monday': 'Montag',
    'booking_hours.tuesday': 'Dienstag',
    'booking_hours.wednesday': 'Mittwoch',
    'booking_hours.thursday': 'Donnerstag',
    'booking_hours.friday': 'Freitag',
    'booking_hours.saturday': 'Samstag',
    'booking_hours.sunday': 'Sonntag',
    'stripe.title': 'Stripe-Einstellungen',
    'stripe.secret_key': 'Stripe Secret Key',
    'stripe.deposit_amount': 'Anzahlungsbetrag',
    'stripe.currency': 'Währung',
    'stripe.save': 'Einstellungen speichern',
    'stripe.saved': 'Stripe-Einstellungen erfolgreich gespeichert!',
    'reservation_widget.title': 'Reservieren Sie Ihren Tisch',
    'reservation_widget.subtitle': 'Buchen Sie Ihre Reservierung bei Patschi',
    'reservation_widget.step_date': 'Datum & Zeit',
    'reservation_widget.step_details': 'Ihre Angaben',
    'reservation_widget.step_confirm': 'Bestätigung',
    'reservation_widget.select_date': 'Datum auswählen',
    'reservation_widget.select_time': 'Zeit auswählen',
    'reservation_widget.party_size': 'Personenanzahl',
    'reservation_widget.select_room': 'Raum auswählen',
    'reservation_widget.next': 'Weiter',
    'reservation_widget.back': 'Zurück',
    'reservation_widget.name': 'Vollständiger Name',
    'reservation_widget.email': 'E-Mail',
    'reservation_widget.phone': 'Telefon (optional)',
    'reservation_widget.special_requests': 'Besondere Wünsche (optional)',
    'reservation_widget.confirm_booking': 'Buchung bestätigen',
    'reservation_widget.success': 'Reservierung bestätigt!',
    'reservation_widget.success_message': 'Ihre Reservierung wurde bestätigt. Sie erhalten in Kürze eine Bestätigungs-E-Mail.',
    'reservation_widget.new_reservation': 'Weitere Reservierung vornehmen',
    'reservation_widget.closed': 'Wir haben an diesem Tag geschlossen',
    'reservation_widget.no_times': 'Keine verfügbaren Zeiten für das ausgewählte Datum',
    'gift_card.title': 'Gutscheinsystem',
    'gift_card.subtitle': 'Geschenkgutscheine & Voucher verwalten',
    'gift_card.home': 'Startseite',
    'gift_card.create_card': 'Gutschein erstellen',
    'gift_card.manage_cards': 'Gutscheine verwalten',
    'gift_card.settings': 'Einstellungen',
    'gift_card.dashboard': 'Gutschein-Dashboard',
    'gift_card.total_sold': 'Verkaufte Gutscheine Gesamt',
    'gift_card.total_revenue': 'Gesamtumsatz',
    'gift_card.active_cards': 'Aktive Gutscheine',
    'gift_card.redeemed_cards': 'Eingelöste Gutscheine',
    'gift_card.recent_sales': 'Aktuelle Gutscheinverkäufe',
    'gift_card.view_all': 'Alle Gutscheine anzeigen',
    'gift_card.no_sales': 'Noch keine Gutscheine verkauft',
    'gift_card.code': 'Code',
    'gift_card.amount': 'Betrag',
    'gift_card.status': 'Status',
    'gift_card.status_active': 'Aktiv',
    'gift_card.status_redeemed': 'Eingelöst',
    'gift_card.status_expired': 'Abgelaufen',
    'gift_card.purchased_by': 'Gekauft von',
    'gift_card.recipient': 'Empfänger',
    'gift_card.balance': 'Guthaben',
    'gift_card.created_date': 'Erstellt',
    'gift_card.expiry_date': 'Gültig bis',
    'gift_card.overview': 'Übersicht Ihres Gutscheinsystems',
    'gift_card.total_value': 'Gesamtwert',
    'gift_card.active_gift_cards': 'Aktive Gutscheine',
    'gift_card.total_cards': 'Gutscheine Gesamt',
    'gift_card.issued_cards': 'Ausgestellte Gutscheine',
    'gift_card.redeemed': 'Eingelöst',
    'gift_card.cards_used': 'Verwendete Gutscheine',
    'system_selector.title': 'Verwaltungssystem auswählen',
    'system_selector.subtitle': 'Wählen Sie das System aus, das Sie verwalten möchten',
    'system_selector.select_system': 'System auswählen',
    'system_selector.reservation_title': 'Reservierungssystem',
    'system_selector.reservation_desc': 'Tischreservierungen, Raumpläne und Buchungszeiten verwalten',
    'system_selector.gift_card_title': 'Gutscheinverwaltung',
    'system_selector.gift_card_desc': 'Gutscheine und Voucher erstellen, verfolgen und verwalten',
    'crew.floor_plan': 'Raumplan',
    'crew.reservations': 'Reservierungen',
    'crew.optional': 'optional',
    'crew.book_multiple_days': 'Für mehrere Tage buchen',
    'crew.book_additional_days': 'Zusätzliche Tage buchen',
    'crew.select_days': 'Tage auswählen',
    'crew.days_selected': 'Tag(e) ausgewählt',
    'crew.additional_reservations_note': '(zusätzliche Reservierungen werden erstellt)',
    'crew.update': 'Aktualisieren',
    'crew.confirm_delete': 'Sind Sie sicher, dass Sie diese Reservierung löschen möchten?',
    'crew.reservation': 'Reservierung',
    'crew.reservations_plural': 'Reservierungen',
    'crew.paid_with_cash': 'Bar bezahlt',
    'crew.cash_amount': 'Barbetrag (€)',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    if (!saved) {
      localStorage.setItem('language', 'de');
      return 'de';
    }
    return (saved === 'en' || saved === 'de') ? saved : 'de';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
